color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.425096
  lightness: 0.220905
  rhythmicContrast: 0.796938
  saturation: 0.520911
layout_spectrum: 0.326577
name: RINLAP
typography_spectrum: 0.942568
